# -*- coding: utf-8 -*-
"""exercicio_03_solyd_lista_de_convidados.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1pvAZZSC6hk8R3t_Oswyf2L84U40qcfw8
"""

print('Lista de Convidados')

numero_de_convidados = input('Digite o número de convidados: ')
lista_de_convidados = []

i = 1



while i <= int(numero_de_convidados):
  nome_do_convidado = input('Digite o nome do convidado #' + str(i) + ': ')
  lista_de_convidados.append(nome_do_convidado)
  i += 1

print('Serão', numero_de_convidados, 'convidados')
print('\nLISTA DE CONVIDADOS:')

for convidado in lista_de_convidados:
  print(convidado)